// Package domain holds the shared domain model for Jarvis Office. It has no dependencies on other
// internal packages, so every other package can import it without cycles.
//
// Conventions (see docs/CONTRACTS.md):
//   - IDs are UUID strings generated by the database (gen_random_uuid()) unless noted.
//   - Money is int64 cents in SGD (type Cents). Reap returns decimal numbers; convert with CentsFromFloat.
//   - Times are UTC time.Time; "month" for budgets is the calendar month in Asia/Singapore.
package domain

import (
	"encoding/json"
	"time"
)

// Role of a (fake-auth) user.
type Role string

const (
	RoleManager  Role = "manager"
	RoleApprover Role = "approver"
	RoleAdmin    Role = "admin"
)

// CanApprove reports whether a role may decide approvals.
func (r Role) CanApprove() bool { return r == RoleApprover || r == RoleAdmin }

// CanAdmin reports whether a role may edit catalog, vendors, policy, addresses and the system prompt.
func (r Role) CanAdmin() bool { return r == RoleAdmin }

// User is a demo user for the fake login.
type User struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	Role      Role      `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

// Vendor is an allow-listed Reap merchant.
type Vendor struct {
	ID     string `json:"id"`
	Domain string `json:"domain"` // unique; also sent as Reap merchantPreference.merchantName
	Name   string `json:"name"`   // display name
	// ReapMerchantName is the exact products[].merchant.name Reap search returns for this merchant.
	// Empty means the merchant was not found in the sandbox. Offers are attributed to a vendor by
	// matching this name (case-sensitive, exact).
	ReapMerchantName string    `json:"reap_merchant_name"`
	Category         string    `json:"category"`
	Country          string    `json:"country"`
	Allowed          bool      `json:"allowed"`
	OfficeRelevant   bool      `json:"office_relevant"`
	Priority         int       `json:"priority"` // lower = more preferred
	Notes            string    `json:"notes"`
	CreatedAt        time.Time `json:"created_at"`
	UpdatedAt        time.Time `json:"updated_at"`
}

// CatalogItem is an approved, pre-vetted item.
type CatalogItem struct {
	ID                 string    `json:"id"`
	SKU                string    `json:"sku"` // stable slug, unique
	Name               string    `json:"name"`
	Aliases            []string  `json:"aliases"`
	Category           string    `json:"category"`
	Unit               string    `json:"unit"`
	DefaultQty         int       `json:"default_qty"`
	MaxUnitPriceCents  Cents     `json:"max_unit_price_cents"`
	PreferredVendorIDs []string  `json:"preferred_vendor_ids"` // ordered, most preferred first
	AutoApprove        bool      `json:"auto_approve"`
	SearchQuery        string    `json:"search_query"`
	Active             bool      `json:"active"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
}

// PolicyConfig is the single office policy row. There is no approval expiry (MVP decision).
type PolicyConfig struct {
	Currency           string    `json:"currency"` // always "SGD" for the MVP
	PerOrderLimitCents Cents     `json:"per_order_limit_cents"`
	MonthlyBudgetCents Cents     `json:"monthly_budget_cents"`
	PriceDriftPct      float64   `json:"price_drift_pct"` // e.g. 5 means 5%
	UpdatedAt          time.Time `json:"updated_at"`
	UpdatedBy          string    `json:"updated_by,omitempty"`
}

// Address is a Singapore delivery address. Fields map onto Reap quote shippingAddress.
type Address struct {
	ID           string    `json:"id"`
	Label        string    `json:"label"`
	FirstName    string    `json:"first_name"`
	LastName     string    `json:"last_name"`
	Phone        string    `json:"phone"` // E.164, e.g. +6562001001
	Email        string    `json:"email"` // used as the Reap quote email
	AddressLine1 string    `json:"address_line1"`
	AddressLine2 string    `json:"address_line2"`
	City         string    `json:"city"`
	Region       string    `json:"region"`
	PostalCode   string    `json:"postal_code"`
	Country      string    `json:"country"` // "SG"
	IsDefault    bool      `json:"is_default"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

// SystemPromptKeyAgent is the key of the prompt shared by the text agent and the realtime session.
const SystemPromptKeyAgent = "agent"

// SystemPrompt is an editable prompt stored in the DB. Version increments on every update.
type SystemPrompt struct {
	Key       string    `json:"key"`
	Content   string    `json:"content"`
	Version   int       `json:"version"`
	UpdatedAt time.Time `json:"updated_at"`
	UpdatedBy string    `json:"updated_by,omitempty"`
}

// EnrollmentStatus mirrors Reap enrollment statuses.
type EnrollmentStatus string

const (
	EnrollmentRequiresAction EnrollmentStatus = "REQUIRES_ACTION"
	EnrollmentActive         EnrollmentStatus = "ACTIVE"
	EnrollmentFailed         EnrollmentStatus = "FAILED"
	EnrollmentExpired        EnrollmentStatus = "EXPIRED"
	EnrollmentRevoked        EnrollmentStatus = "REVOKED"
)

// Enrollment is our record of a Reap EXTERNAL card enrollment. We never store card data:
// no PAN, no expiry, no last4, only Reap's id and status.
type Enrollment struct {
	ID               string           `json:"id"`
	ReapEnrollmentID string           `json:"reap_enrollment_id"`
	Status           EnrollmentStatus `json:"status"`
	OwnerRef         string           `json:"owner_ref"` // CLIENT_REFERENCE id we sent (the user id)
	OwnerEmail       string           `json:"owner_email"`
	NextActionURL    string           `json:"next_action_url,omitempty"` // hosted card-entry page
	CreatedBy        string           `json:"created_by"`
	CreatedAt        time.Time        `json:"created_at"`
	UpdatedAt        time.Time        `json:"updated_at"`
}

// Urgency of a requested line item.
type Urgency string

const (
	UrgencyNormal Urgency = "normal"
	UrgencyUrgent Urgency = "urgent"
)

// PurchaseRequest is the spine of the flow. See status.go for the state machine.
type PurchaseRequest struct {
	ID            string        `json:"id"`
	RequesterID   string        `json:"requester_id"`
	RawUtterance  string        `json:"raw_utterance"`
	Status        RequestStatus `json:"status"`
	AddressID     *string       `json:"address_id,omitempty"` // set on confirm
	SubtotalCents Cents         `json:"subtotal_cents"`       // sum of selected offers' unit*qty
	ShippingCents Cents         `json:"shipping_cents"`       // estimated (search) or live (quote)
	TotalCents    Cents         `json:"total_cents"`          // approved/expected landed total
	Currency      string        `json:"currency"`
	Decision      Decision      `json:"decision,omitempty"` // overall policy decision, empty until evaluated
	FailureReason string        `json:"failure_reason,omitempty"`
	ConfirmedBy   *string       `json:"confirmed_by,omitempty"`
	ConfirmedAt   *time.Time    `json:"confirmed_at,omitempty"`
	CreatedAt     time.Time     `json:"created_at"`
	UpdatedAt     time.Time     `json:"updated_at"`
}

// Decision is the deterministic policy outcome.
type Decision string

const (
	DecisionAutoApprove   Decision = "AUTO_APPROVE"
	DecisionNeedsApproval Decision = "NEEDS_APPROVAL"
	DecisionReject        Decision = "REJECT"
)

// ReasonCode explains a policy decision. Codes are stable strings the UI can map to copy.
type ReasonCode string

const (
	ReasonOffList           ReasonCode = "OFF_LIST"            // no catalog match
	ReasonNotAutoApprove    ReasonCode = "NOT_AUTO_APPROVE"    // catalog item flagged auto_approve=false
	ReasonOverUnitCeiling   ReasonCode = "OVER_UNIT_CEILING"   // unit price > catalog max_unit_price
	ReasonOverOrderLimit    ReasonCode = "OVER_ORDER_LIMIT"    // request total > per-order limit
	ReasonOverMonthlyBudget ReasonCode = "OVER_MONTHLY_BUDGET" // month spend + total > budget
	ReasonVendorNotAllowed  ReasonCode = "VENDOR_NOT_ALLOWED"  // best offer is from a non-allowed merchant
	ReasonNoOffer           ReasonCode = "NO_OFFER"            // no available offer at an allowed vendor
	ReasonPriceDrift        ReasonCode = "PRICE_DRIFT"         // live quote exceeded approved total by > drift pct
	ReasonCurrencyMismatch  ReasonCode = "CURRENCY_MISMATCH"   // offer not in SGD
)

// Reason is a code plus a human readable message (message is generated by code, not by an LLM).
type Reason struct {
	Code    ReasonCode `json:"code"`
	Message string     `json:"message"`
}

// LineItem is one requested item within a request.
type LineItem struct {
	ID              string    `json:"id"`
	RequestID       string    `json:"request_id"`
	Position        int       `json:"position"`
	CatalogItemID   *string   `json:"catalog_item_id,omitempty"` // nil = off-list
	Description     string    `json:"description"`               // what the user asked for, normalised
	Qty             int       `json:"qty"`
	Urgency         Urgency   `json:"urgency"`
	PolicyDecision  Decision  `json:"policy_decision,omitempty"`
	Reasons         []Reason  `json:"reasons"`
	SelectedOfferID *string   `json:"selected_offer_id,omitempty"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

// Offer is a normalised product offer found by a search agent (from Reap search/details).
type Offer struct {
	ID              string    `json:"id"`
	LineItemID      string    `json:"line_item_id"`
	VendorID        *string   `json:"vendor_id,omitempty"` // nil if merchant is not a known vendor
	MerchantName    string    `json:"merchant_name"`       // Reap merchant.name
	ReapProductID   string    `json:"reap_product_id"`
	ReapVariantID   string    `json:"reap_variant_id"`
	Title           string    `json:"title"`
	VariantName     string    `json:"variant_name,omitempty"`
	ImageURL        string    `json:"image_url,omitempty"`
	URL             string    `json:"url,omitempty"`
	UnitPriceCents  Cents     `json:"unit_price_cents"` // price of one purchasable variant
	Currency        string    `json:"currency"`
	PackSize        int       `json:"pack_size"`         // units per variant (1 if unknown)
	ShippingCents   Cents     `json:"shipping_cents"`    // estimate; 0 if unknown at search time
	LandedCostCents Cents     `json:"landed_cost_cents"` // unit*qty + shipping (+tax if known)
	ETA             string    `json:"eta,omitempty"`     // free text from merchant, if any
	Available       bool      `json:"available"`
	Rank            int       `json:"rank"` // 1 = best
	CreatedAt       time.Time `json:"created_at"`
	// Description is a short plain-text product summary used only to judge relevance while
	// ranking. Transient: not persisted and not part of the API.
	Description string `json:"-"`
}

// ApprovalStatus of an approval task.
type ApprovalStatus string

const (
	ApprovalPending  ApprovalStatus = "pending"
	ApprovalApproved ApprovalStatus = "approved"
	ApprovalRejected ApprovalStatus = "rejected"
)

// ApprovalKind says why the approval exists.
type ApprovalKind string

const (
	ApprovalKindPolicy     ApprovalKind = "policy"      // NEEDS_APPROVAL from the policy engine
	ApprovalKindPriceDrift ApprovalKind = "price_drift" // live Reap quote drifted past threshold
)

// Approval is created only on NEEDS_APPROVAL (or price drift). No expiry.
type Approval struct {
	ID          string         `json:"id"`
	RequestID   string         `json:"request_id"`
	Kind        ApprovalKind   `json:"kind"`
	Status      ApprovalStatus `json:"status"`
	Reasons     []Reason       `json:"reasons"`
	AmountCents Cents          `json:"amount_cents"`         // total the approver is approving
	PrevCents   *Cents         `json:"prev_cents,omitempty"` // for price_drift: previously approved total
	ApproverID  *string        `json:"approver_id,omitempty"`
	Comment     string         `json:"comment,omitempty"`
	DecidedAt   *time.Time     `json:"decided_at,omitempty"`
	CreatedAt   time.Time      `json:"created_at"`
}

// PaymentStatus tracks one Reap quote+checkout (one per merchant in the basket).
type PaymentStatus string

const (
	PaymentQuoting        PaymentStatus = "quoting"         // creating Reap quote
	PaymentQuoted         PaymentStatus = "quoted"          // quote ok, drift checked
	PaymentRequiresAction PaymentStatus = "requires_action" // checkout created; user must open approval URL
	PaymentProcessing     PaymentStatus = "processing"
	PaymentCompleted      PaymentStatus = "completed"
	PaymentFailed         PaymentStatus = "failed"
	PaymentExpired        PaymentStatus = "expired"
)

// Payment maps one-to-one to a Reap quote + checkout for a single merchant.
type Payment struct {
	ID             string        `json:"id"`
	RequestID      string        `json:"request_id"`
	VendorID       *string       `json:"vendor_id,omitempty"`
	MerchantName   string        `json:"merchant_name"`
	EnrollmentID   *string       `json:"enrollment_id,omitempty"` // our enrollment row id
	ReapQuoteID    string        `json:"reap_quote_id,omitempty"`
	ReapCheckoutID string        `json:"reap_checkout_id,omitempty"`
	ReapOrderID    string        `json:"reap_order_id,omitempty"`
	ItemsCents     Cents         `json:"items_cents"`
	ShippingCents  Cents         `json:"shipping_cents"`
	TaxCents       Cents         `json:"tax_cents"`
	QuotedCents    Cents         `json:"quoted_cents"`          // quote amountBreakdown.finalAmount
	FinalCents     *Cents        `json:"final_cents,omitempty"` // checkout finalAmount (actually charged)
	Currency       string        `json:"currency"`
	Status         PaymentStatus `json:"status"`
	ApprovalURL    string        `json:"approval_url,omitempty"` // checkout nextAction.url (Reap-hosted)
	QuoteExpiresAt *time.Time    `json:"quote_expires_at,omitempty"`
	IdempotencyKey string        `json:"-"`
	// QuoteAttempt selects the quote idempotency key generation (0 = "<key>:quote").
	QuoteAttempt int       `json:"-"`
	Error        string    `json:"error,omitempty"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

// ActorType of an audit event.
type ActorType string

const (
	ActorUser   ActorType = "user"
	ActorAgent  ActorType = "agent"
	ActorSystem ActorType = "system"
)

// AuditEvent is append-only. Never update or delete rows.
type AuditEvent struct {
	ID        int64           `json:"id"`
	RequestID *string         `json:"request_id,omitempty"`
	ActorType ActorType       `json:"actor_type"`
	ActorID   string          `json:"actor_id,omitempty"`
	Type      string          `json:"type"` // dotted, e.g. "request.created", see audit package
	Payload   json.RawMessage `json:"payload,omitempty"`
	At        time.Time       `json:"at"`
}

// ChatRole of a stored agent conversation message.
type ChatRole string

const (
	ChatRoleSystem    ChatRole = "system"
	ChatRoleUser      ChatRole = "user"
	ChatRoleAssistant ChatRole = "assistant"
	ChatRoleTool      ChatRole = "tool"
)

// ChatMessage is one message of a text-agent session (persisted so refresh/restart keeps context).
type ChatMessage struct {
	ID         int64           `json:"id"`
	SessionID  string          `json:"session_id"`
	UserID     string          `json:"user_id,omitempty"`
	Role       ChatRole        `json:"role"`
	Content    string          `json:"content"`
	ToolCalls  json.RawMessage `json:"tool_calls,omitempty"` // []llm.ToolCall as JSON, assistant only
	ToolCallID string          `json:"tool_call_id,omitempty"`
	CreatedAt  time.Time       `json:"created_at"`
}

// MonthSpend is completed spend for a calendar month (Asia/Singapore), for charts.
type MonthSpend struct {
	Month      string `json:"month"` // "2026-10"
	SpendCents Cents  `json:"spend_cents"`
	Orders     int    `json:"orders"`
}

// RequestDetail is the aggregate the API returns for one request.
type RequestDetail struct {
	Request   PurchaseRequest `json:"request"`
	LineItems []LineItem      `json:"line_items"`
	Offers    []Offer         `json:"offers"` // all offers for all line items, ranked per line item
	Approvals []Approval      `json:"approvals"`
	Payments  []Payment       `json:"payments"`
	Address   *Address        `json:"address,omitempty"`
}
